version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vault_db
    environment:
      POSTGRES_USER: errl
      POSTGRES_PASSWORD: errlpassword
      POSTGRES_DB: component_vault
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: vault_queue
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
